apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypersistantefsvol
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs-9613b1df.efs.us-east-1.amazonaws.com
    path: "/jenkindata"
